version: 2
jobs:
  publish-latest:
    environment:
      IMAGE_NAME: define42/openwebui
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker images
            docker pull  ghcr.io/open-webui/open-webui:main
            docker tag  ghcr.io/open-webui/open-webui:main $IMAGE_NAME:latest
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - publish-latest:
          filters:
            branches:
              only: main
